# ======
# Project Details
# ======
name: 'name'
version: '1.0'
config-version: 2
profile: 'revel_analytics'
require-dbt-version: 1.2.0

# ======
# File Path Configs
# ======
model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
analysis-paths: ["analysis"]
target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"